#define _COROUTINE_CONCAT_1(x, y) x ## y
#define _COROUTINE_CONCAT_2(x, y) _COROUTINE_CONCAT_1(x, y)

#if _COROUTINE_COUNTER == 0
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 1
#elif _COROUTINE_COUNTER == 1
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 2
#elif _COROUTINE_COUNTER == 2
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 3
#elif _COROUTINE_COUNTER == 3
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 4
#elif _COROUTINE_COUNTER == 4
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 5
#elif _COROUTINE_COUNTER == 5
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 6
#elif _COROUTINE_COUNTER == 6
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 7
#elif _COROUTINE_COUNTER == 7
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 8
#elif _COROUTINE_COUNTER == 8
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 9
#elif _COROUTINE_COUNTER == 9
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 10
#elif _COROUTINE_COUNTER == 10
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 11
#elif _COROUTINE_COUNTER == 11
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 12
#elif _COROUTINE_COUNTER == 12
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 13
#elif _COROUTINE_COUNTER == 13
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 14
#elif _COROUTINE_COUNTER == 14
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 15
#elif _COROUTINE_COUNTER == 15
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 16
#elif _COROUTINE_COUNTER == 16
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 17
#elif _COROUTINE_COUNTER == 17
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 18
#elif _COROUTINE_COUNTER == 18
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 19
#elif _COROUTINE_COUNTER == 19
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 20
#elif _COROUTINE_COUNTER == 20
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 21
#elif _COROUTINE_COUNTER == 21
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 22
#elif _COROUTINE_COUNTER == 22
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 23
#elif _COROUTINE_COUNTER == 23
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 24
#elif _COROUTINE_COUNTER == 24
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 25
#elif _COROUTINE_COUNTER == 25
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 26
#elif _COROUTINE_COUNTER == 26
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 27
#elif _COROUTINE_COUNTER == 27
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 28
#elif _COROUTINE_COUNTER == 28
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 29
#elif _COROUTINE_COUNTER == 29
#undef _COROUTINE_COUNTER
#define _COROUTINE_COUNTER 30
#elif
#error "No more than 30 yield slots are enabled. To enable more, add more conditions to co/yield.h and co/end.h"
#endif

_co->i = _COROUTINE_COUNTER;
return;
_COROUTINE_CONCAT_2(__coroutine_yield_, _COROUTINE_COUNTER):
(void) _co;

#undef _COROUTINE_CONCAT_1
#undef _COROUTINE_CONCAT_2
